### ISSUE TITLE
なんかもっと良いやり方があるような…

### ISSUE THREAD

**Issue by an2023043** [watanabeayumi/ACEPROJECT2#18]
https://github.com/watanabeayumi/ACEPROJECT2/blob/04998d7150da51295fe8e07daa5feb68766f09d0/src/main/java/reserve/servlet/ReserveConfirmServlet.java#LL56C1-L68C4

**Comment by risakuroda** [comment]
完了しました。確認お願いします。

**Comment by an2023043** [comment]
確認しました。
