### ISSUE TITLE
ReserveDAOのインスタンスをfor文の前に設定し、それを使う

### ISSUE THREAD

**Issue by an2023043** [watanabeayumi/ACEPROJECT2#19]
https://github.com/watanabeayumi/ACEPROJECT2/blob/93a73b77d69517beaa2ec3914ed31a10c8ae5f29/src/main/java/reserve/servlet/ReserveConfirmServlet.java#LL71C3-L81C4

**Comment by risakuroda** [comment]
完了しました。確認お願いします。

**Comment by an2023043** [comment]
確認できました。
